# Generated by Django 2.2 on 2021-05-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lottery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('enable', models.BooleanField(default=True, verbose_name='是否可用')),
                ('active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('issue', models.CharField(max_length=32, verbose_name='期')),
                ('type', models.CharField(max_length=32, verbose_name='类型')),
                ('num', models.CharField(max_length=128, verbose_name='号码')),
            ],
            options={
                'verbose_name': '幸运号码',
                'verbose_name_plural': '幸运号码',
            },
        ),
    ]
